---
abstract: 'Lures nearby data with its enchanting structures.'
author:
  - 'Mike Raynham <enquiries@mikeraynham.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Siren
version: '0.001'
